apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.4.0
  values:
    controller:
      kind: DaemonSet
      metrics:
        enabled: true
      watchIngressWithoutClass: true
      config:
        use-forwarded-headers: true
        forwarded-for-header: "CF-Connecting-IP"
        proxy-real-ip-cidr: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,10.0.0.0/8" # cloudflare ipv4 & vlan-eu
        compute-full-forwarded-for: true
      service:
        enabled: true
        type: LoadBalancer
      resources:
        requests:
          cpu: "1m" # force it to deploy on a node
  interval: 30m
