apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ofdiJ1Tf6ATz8gIzeitzqBXsO0xgNAJfAVDsyL3tph8=,iv:4ax3WCvCbC2g8nmHyaW/wUcZv46vIVGiMuHvcZbU12s=,tag:aHm6cdjFCaAKcwdKTvwvRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gj08c8zsqrgn3nkxdnf0m6cjmpruvrnnapvztjgja8nh3w5c9lqh4ag3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ1ZDeW5CRUhtdnl6L2VR
            NXRKSkphYnJ4QXVDcWxUSUlJK0kwYXhCS1hFCkdqbU44eUNYNzRoTWhwUVJsMXVh
            QUVxZVphaVZTWlVHN21pdnEwb3lRL3cKLS0tIGllQlc0SGVkamxXdHR5VW9mT2I1
            dHNTdDQ0TkZJdzNQZFgvRXFzWlZtK1UK2P1BM84v5vqXgsf2NuSgzQrnLO0SBgNn
            o4gRN7ZChvS8R1g0/E612FyMnL4zxlToYHbUK41OnjjyXsQWzdyGHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T20:45:37Z"
    mac: ENC[AES256_GCM,data:CE6BlyxCXusvjYRBtI7C4M9vtyU4alpGvgYWe059gaFxkStugX7EPOUpWE9h+wjlnl8wpDnVR6rJIpmEgnxXoqctd1QeWfFwih4oNY64ksxe97/LcRtcVryza7Bh2bxbit6LcFZwtKdD1KpwTzGPbz6SCsOBQ8wsQ4Z5dT61/58=,iv:0w+KS+1g10RTdKLgUdRMDFjJzupCjdbVSCP2G7Y4Ji4=,tag:G2Y7Df7x/x1IsUSEfVwr3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
