apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon-chart
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    commit: b8c8a7e482923b9d282b1d3e40bc92290db4222a
  url: https://github.com/clrxbl/mastodon-chart.git
