apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon-chart
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    commit: 628fb35ce2aac46c79cac02b5b39f6b45cb061a8
  url: https://github.com/clrxbl/mastodon-chart.git
