apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon-chart
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    commit: 77ce6a071a0f9331672e05a3ddb2e2e1be31b065
  url: https://github.com/clrxbl/mastodon-chart.git
