apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon-chart
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    commit: 2d96be1514112b3e9ac6bbf7c6cf0a9a81aa9d22
  url: https://github.com/clrxbl/mastodon-chart.git
