apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: mastodon-chart
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    image:
      repository: yakumosaki/glitch-soc
      tag: "20230830_01"
    replicaCount: 1
    mastodon:
      preparedStatements: false
      createAdmin:
        enabled: false # generate an admin user through CLI
      local_domain: "crunchy.social"
      s3:
        enabled: true
        bucket: "assets.crunchy.social"
        endpoint: "https://nyc3.digitaloceanspaces.com"
        hostname: "assets.crunchy.social"
        region: "nyc3"
        alias_host: "assets.crunchy.social"
        existingSecret: "mastodon-secrets"
      secrets:
        existingSecret: "mastodon-secrets"
      smtp:
        domain: crunchy.social
        from_address: "void@crunchy.social"
        port: 587
        server: "email-smtp.us-east-1.amazonaws.com"
        tls: false
        enable_starttls: true
        existingSecret: "mastodon-secrets"
      streaming:
        rejectUnauthorizedTls: "0" # DO Managed Databases use self-signed certs and we do not have the ability to add our own certs without a custom image
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.crunchy.social
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
      hosts:
        - host: crunchy.social
          paths:
            - path: '/'
      tls:
        - secretName: wildcard-crunchy-social-tls
          hosts:
            - crunchy.social
    elasticsearch:
      enabled: false
    redis:
      enabled: false
      hostname: "keydb"
      port: 6379
      auth:
        existingSecret: "mastodon-secrets"
    postgresql:
      enabled: false
      postgresqlHostname: "private-mastodon-psql-do-user-1072553-0.b.db.ondigitalocean.com"
      postgresqlPort: 25061
      auth:
        database: mastodon
        username: mastodon
        existingSecret: "mastodon-psql-credentials"
        sslMode: "require"
  interval: 30m
