apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: mastodon-chart
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    replicaCount: 1
    mastodon:
      createAdmin:
        enabled: false # generate an admin user through CLI
      local_domain: "p2w.social"
      persistence:
        assets:
          resources:
            requests:
              storage: 10Gi
        system:
          resources:
            requests:
              storage: 10Gi
      s3:
        enabled: false # setup S3 in a bit
      secrets:
        existingSecret: "mastodon-secrets"
      smtp:
        domain: p2w.social
        from_address: "void@p2w.social"
        port: 587
        server: "smtp.postmarkapp.com"
        tls: true
        existingSecret: "mastodon-secrets"
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.p2w.social
      hosts:
        - host: p2w.social
          paths:
            - path: '/'
      tls:
        - secretName: wildcard-p2w-social-tls
          hosts:
            - p2w.social
    elasticsearch:
      enabled: false
    redis:
      enabled: false
      hostname: "keydb"
      port: 6379
      auth:
        existingSecret: "mastodon-secrets"
    postgresql:
      enabled: false
      postgresqlHostname: "private-mastodon-psql-do-user-1072553-0.b.db.ondigitalocean.com"
      postgresqlPort: 25061
      auth:
        database: mastodon
        username: mastodon
        existingSecret: "mastodon-psql-credentials"
  interval: 30m
