apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keydb
  namespace: mastodon
spec:
  chart:
    spec:
      chart: keydb
      sourceRef:
        kind: HelmRepository
        name: enapter
        namespace: flux-system
      version: 0.43.1
  values:
    persistentVolume:
      enabled: false
    nodes: 1
    image: eqalpha/keydb:x86_64_v6.2.2
  interval: 30m
