apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secrets
    namespace: mastodon
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:UXfkVpi6y0W3kwu8w+8JsI8xqgOuW2cAG8+8clmuwnYC0RgHDZHl2o4hMrEnTaWZTGtrZtcilYPPBoecakP0iHKA4TfMleWztS/SS2acp0EqiVCD5JUPxVbno3lrp8sGFGCBqu4Agf5+hTrIlB750gFHO19SuBrR1qXiumnvQH4=,iv:vOOWqYffWBpGQJyqUe5XpYE+Wza/7GmDYVnBfmFpcx4=,tag:CwH9VUU0o9IdcCE6mtkWEw==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:55nKjKUpYxD9yOJGePYZNr577F1/R48ExAuz6tokf2OaodAbYZ5XZaKhy1x8A8eHrDhJ/cgXbvzWVaXTTyD7iDZ8aim7knLU627CXhx1iar2ibtfXnesAssMGRrGClKBc8xGjZwid71ScANG+BkZjeOIU1gcvFcz2MXyszUx1j0=,iv:QymLMuh9hPFIKd2MO6ao509C3AhRgjRsRSyeUghyIvo=,tag:QS1SbN4QP303xLUc6az5ag==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:jQ7oTSi/ClieO/VDFyYTgSA7v0mjqShhEWFJKNzMLRCdn29uOzFgZbgPU7Q=,iv:SYj2NjqDHfbZrYzkZBXsV+jC+bRlIT0cEKEav5TLvAg=,tag:6UAu+FAhrq1kXhxGuPn7zw==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:eQ0SLpbz1MdCuPUbVroEfo5Ots7lOu06JErME9fQWXadLHvK2BIWcAg5ba1syjAfxgeAHkLhRWfxVMLnFg8QkXaXPWSB14XHdtnIFTvCo8OJWBRHSewxFA==,iv:IfOh2rA0X2QeALogNJ2Z2Mnah/Nu1nowihLB38+K8rg=,tag:CGb0tgabR+spkmfT1VP9lQ==,type:str]
    login: ENC[AES256_GCM,data:y2CS982xxn2P8Ao6LXOe4uRpML6/n+t+4LGWs6h6BvNbL+oL,iv:Yf6Oo6uAuI2QBeFy2HsiFuh8ZspbFJv7AL4gQ/rNqsc=,tag:HUxi6JnvdMDXmw7PGDwGSw==,type:str]
    password: ENC[AES256_GCM,data:fEoTDvxSUrbjnNeQTK1uf6UVoV/eOsPwH9Dug6IrgAWk9GfO,iv:bgxr8V9LS2rUDTrq9Y0Q9VAFaNk6/ryHHEYBwFGhOg0=,tag:vCBViaUCzJfCqZS1yKbJjQ==,type:str]
    redis-password: ENC[AES256_GCM,data:qUSQAw0y3sVkeLIFI8FPNSCMIF9x9yoV/WlsX6Ck96Q=,iv:BtsS8V73/m6lXR5MnN+3p0v2qswi7yqcCV8txrY94pg=,tag:j04Pj/4EKRaFRKybNqVTPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gj08c8zsqrgn3nkxdnf0m6cjmpruvrnnapvztjgja8nh3w5c9lqh4ag3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWpHcnRnTWx3eUVpZm1a
            clBBWnk5SmZYZDhYbkpLNG5WZFpCalJ3MkdNClh3dzNVeTZPWVV1dk4yV0NFbUVT
            cjVqOUNsbjJ4OGpseUxDMDNKM3l3NEkKLS0tIFdiUjRXVk4wL2pMc2lCZXJlU3Nn
            Ulc2SmZGSnJBYlZYV0d2Y3Q5VXZtUU0K4crMAJxbmbmbR/923xusGvgoeImZ8TGQ
            Y4dNbgSol8T9yPRs9fwpt734kqBPDcZEJXzhKPNvBlLVdvgo4hmf6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-19T00:28:01Z"
    mac: ENC[AES256_GCM,data:kqJHOWja5Y6TQjMRz+1VB1ZU6m2VterTlrXRLIBRgvj60oqWSZ/tOQOGfOCi52U3lQL4uzjKN99+Nh4gW3BSQ+rbmnRpJQLI6lax+CG2eIb7cZu24YAjXMqkgJ8UHyQMMsctPCKvM7I1sCuskpZwa5HIX7ePtvqkKLRPdTbNOVg=,iv:/uuLdwevGMe6ivdQThOU7LM/uW7hNsWwICg8PWZ9sVU=,tag:PFP9ihbN9XcPkwd/ZO6dXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
