apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-crunchy-social
  namespace: kube-system
spec:
  secretName: wildcard-crunchy-social-tls
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "*"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - '*.crunchy.social'
