apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kubernetes-replicator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      version: 2.7.3
  interval: 30m
