apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mastodon/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: mastodon-psql-private-connection
        namespace: mastodon
        optional: true
      - kind: Secret
        name: mastodon-psql-credentials
        namespace: mastodon
        optional: true
